name: create-springboot-project

on:
  workflow_dispatch:
    inputs:
      project_name:
        required: true
      java_version:
        default: "17"
      spring_version:
        default: "3.5.13"
      dependencies:
        default: "web,validation,actuator,data-jpa,postgresql,lombok,springdoc-openapi"

jobs:
  generate-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate inputs
        run: |
          # whitelist project name
          if ! [[ "${{ github.event.inputs.project_name }}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "❌ Invalid project name"; exit 1;
          fi

          # whitelist dependencies
          if ! [[ "${{ github.event.inputs.dependencies }}" =~ ^[a-zA-Z0-9,.-]+$ ]]; then
            echo "❌ Invalid dependency list"; exit 1;
          fi

      - name: Generate Spring Boot project
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          SPRING_VERSION: ${{ github.event.inputs.spring_version }}
          JAVA_VERSION: ${{ github.event.inputs.java_version }}
          DEP: ${{ github.event.inputs.dependencies }}
        run: |
          set -e

          mkdir "${PROJECT_NAME}"
          cd "${PROJECT_NAME}"

          DEP_CLEAN=$(echo "$DEP" | tr -d '[:space:]')

          echo "Dependencies used = $DEP_CLEAN"

          curl -fSL \
            -o project.zip \
            "https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=${SPRING_VERSION}&dependencies=${DEP_CLEAN}&packageName=com.sogeti.temp&configYaml=true&javaVersion=${JAVA_VERSION}"

          unzip project.zip -d .
          rm project.zip

      - name: Security - Scan dependencies (Trivy)
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: filesystem
          severity: CRITICAL,HIGH

      - name: Generate Dockerfile & CI
        env:
          SCRIPT_FILE: ${{ github.workspace }}/scripts/generate-dockerfile.sh
          CI_FILE: ${{ github.workspace }}/scripts/generate-ci-file.sh
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          set -e
          chmod +x "$SCRIPT_FILE" "$CI_FILE"
          cd "${PROJECT_NAME}"
          bash "$SCRIPT_FILE"
          bash "$CI_FILE"

      - name: Build package structure
        run: |
          set -e
          cd "${{ github.event.inputs.project_name }}"

          ROOT_DIR="src/main/java/com/sogeti/${{ github.event.inputs.project_name }}"
          mkdir -p $ROOT_DIR/{config,controller,service,repository,domain,exception,utils}

          OLD_PKG="src/main/java/com/sogeti/temp"
          if [ -d "$OLD_PKG" ]; then
            mv ${OLD_PKG}/* $ROOT_DIR/
            rm -rf ${OLD_PKG}
          fi

          # Secure sed replace
          find src/main/java -type f -name "*.java" \
            -exec sed -i "s|com.sogeti.temp|com.sogeti.${{ github.event.inputs.project_name }}|g" {} \;

      - uses: actions/upload-artifact@v4
        with:
          name: generated-project
          path: ${{ github.workspace }}/${{ github.event.inputs.project_name }}
          if-no-files-found: error

  create-repo:
    runs-on: ubuntu-latest
    needs: generate-project

    steps:
      - name: Download generated project
        uses: actions/download-artifact@v4
        with:
          name: generated-project
          path: workspace

      - name: Create GitHub Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          curl -f -s \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"name\": \"${PROJECT_NAME}\", \"private\": false }" \
            https://api.github.com/user/repos

          sleep 4

  push-code:
    runs-on: ubuntu-latest
    needs: create-repo

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generated-project
          path: workspace
      # Ensure project exist 
      - name: Ensure project folder exists
        run: |
          if [ ! -d "workspace/${PROJECT_NAME}" ]; then
            echo "❌ ERROR: workspace/${PROJECT_NAME} does not exist"
            echo "Check artifact content and generation step."
            ls -R workspace
            exit 1
          fi
      - name: Push project
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          USERNAME: ${{ secrets.GH_USERNAME }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          cd "workspace/${PROJECT_NAME}"
          git init
          git config user.name "github-actions"
          git config user.email "ci-bot@github.com"
          git add .
          git commit -m "Initial auto-generated Spring Boot project"
          git branch -M main
          git remote add origin https://${USERNAME}:${GH_PAT}@github.com/${USERNAME}/${PROJECT_NAME}.git
          git push -u origin main
