name: create-springboot-project

on:
  workflow_dispatch:
    inputs:
      project_name:
        required: true
      spring_version:
        description: "Version Spring Boot"
        default: "3.5.13"
      dependencies:
        description: "List of default dependencies"
        default: "web,validation,actuator,data-jpa,postgres,lombok,springdoc-openapi"

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          curl -H "Authorization: token $GH_PAT" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/user/repos \
               -d "{\"name\": \"${PROJECT_NAME}\", \"private\": false }"

      - name: Generate Spring Boot project
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          SPRING_VERSION: ${{ github.event.inputs.spring_version }}
          DEP: ${{ github.event.inputs.dependencies }}
        run: |
          mkdir ${PROJECT_NAME}
          cd ${PROJECT_NAME}
          echo "➡️ Downloading Spring Boot project..."
          
          curl -s -L -o project.zip "https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=${SPRING_VERSION}&dependencies=${DEP}&packageName=com.sogeti.temp"
              
          echo "📡 HTTP CODE: ${HTTP_CODE}"
          
          if [ "$HTTP_CODE" -ne 200 ]; then
                  echo "❌ ERROR: Spring Initializr returned HTTP $HTTP_CODE"
                  echo "👉 Saving response body for debugging..."
                  curl -s "https://start.spring.io/starter.zip?bootVersion=${SPRING_VERSION}&dependencies=${DEP}&type=maven-project&language=java&packageName=com.sogeti.temp" -o error-response.bin
                  echo "⚠️ Saved as error-response.bin"
                  exit 1
              fi

          echo "➡️ Validating ZIP file..."
              if ! unzip -t project.zip > /dev/null 2>&1; then
                  echo "❌ ERROR: The downloaded file is NOT a valid zip."
                  echo "👉 Saving file for analysis as project.zip.broken"
                  mv project.zip project.zip.broken
                  exit 1
              fi
          
              echo "✅ ZIP is valid. Proceeding with extraction."

          unzip project.zip
          rm project.zip

      - name: Build custom package structure
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          cd ${PROJECT_NAME}

          ROOT_DIR="src/main/java/com/sogeti/${PROJECT_NAME}"

          mkdir -p ${ROOT_DIR}/config
          mkdir -p ${ROOT_DIR}/controller
          mkdir -p ${ROOT_DIR}/service
          mkdir -p ${ROOT_DIR}/repository
          mkdir -p ${ROOT_DIR}/domain
          mkdir -p ${ROOT_DIR}/exception
          mkdir -p ${ROOT_DIR}/utils

          # move content generate
          OLD_PKG="src/main/java/com/sogeti/temp"
          if [ -d "$OLD_PKG" ]; then
            mv ${OLD_PKG}/* ${ROOT_DIR}/
            rm -rf ${OLD_PKG}
          fi

          #update packages declarations
          find src/main/java -type f -name "*.java" -exec \
            sed -i "s/com.sogeti.temp/com.sogeti.${PROJECT_NAME}/g" {} \;

      - name: Push project to new GitHub repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          USERNAME: ${{ secrets.GH_USERNAME }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          cd ${PROJECT_NAME}
          git init
          git config user.email "ci-bot@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Initial Spring Boot project with custom structure"
          git branch -M main
          git remote add origin https://${USERNAME}:${GH_PAT}@github.com/${USERNAME}/${PROJECT_NAME}.git
          git push -u origin main
