name: create-springboot-project

on:
  workflow_dispatch:
    inputs:
      project_name:
        required: true
      java_version:
        description: "Java Version"
        default: "17"
      spring_version:
        description: "Version Spring Boot"
        default: "3.5.13"
      dependencies:
        description: "List of default dependencies"
        default: "web,validation,actuator,data-jpa,postgresql,lombok,springdoc-openapi"

jobs:
  generate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Spring Boot project
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          SPRING_VERSION: ${{ github.event.inputs.spring_version }}
          JAVA_VERSION: ${{ github.event.inputs.java_version }}
          DEP: ${{ github.event.inputs.dependencies }}
        run: |
          mkdir ${PROJECT_NAME}
          cd ${PROJECT_NAME}
          
          DEP_CLEAN=$(echo "$DEP" | tr -d '[:space:]' | tr -cd 'a-zA-Z0-9,.-')
          echo "CLEANED DEPENDENCIES = $DEP_CLEAN"

          curl -s -L -o project.zip "https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=${SPRING_VERSION}&dependencies=${DEP_CLEAN}&packageName=com.sogeti.temp&configYaml=true&javaVersion=${JAVA_VERSION"
          
          unzip project.zip
          rm project.zip
      ############################################################
      # 3. GENERATE DOCKERFILE
      ############################################################
      - name: Generate Dockerfile
        env:
          SCRIPT_FILE: ${{ github.workspace }}/scripts/generate-dockerfile.sh
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          set -e
          echo "Running script: ${SCRIPT_FILE}"
          chmod +x "${SCRIPT_FILE}"
          cd ${PROJECT_NAME}
          bash ${SCRIPT_FILE}

      - name: Build custom package structure
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          set -e
          cd ${PROJECT_NAME}

          ROOT_DIR="src/main/java/com/sogeti/${PROJECT_NAME}"

          mkdir -p ${ROOT_DIR}/config
          mkdir -p ${ROOT_DIR}/controller
          mkdir -p ${ROOT_DIR}/service
          mkdir -p ${ROOT_DIR}/repository
          mkdir -p ${ROOT_DIR}/domain
          mkdir -p ${ROOT_DIR}/exception
          mkdir -p ${ROOT_DIR}/utils

          # move content generate
          OLD_PKG="src/main/java/com/sogeti/temp"
          if [ -d "$OLD_PKG" ]; then
            mv ${OLD_PKG}/* ${ROOT_DIR}/
            rm -rf ${OLD_PKG}
          fi

          #update packages declarations
          find src/main/java -type f -name "*.java" -exec \
            sed -i "s/com.sogeti.temp/com.sogeti.${PROJECT_NAME}/g" {} \;

      - name: Upload generated project
        uses: actions/upload-artifact@v4
        with:
          name: generated-project
          path: ${{ github.event.inputs.project_name }}
          if-no-files-found: error
      ############################################################
      # 3. CREATE REPO ONLY IF EVERYTHING PASSED SUCCESSFULLY
      ############################################################
  create-repo:
    runs-on: ubuntu-latest
    needs: generate-project
    steps:
      
      - name: Download generated project
        uses: actions/download-artifact@v4
        with:
          name: generated-project
          path: workspace

      - name: Create GitHub Repository (only after success)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          echo "Creating repository only now (strategy A)..."
          curl -s -H "Authorization: token $GH_PAT" \
                -H "Accept: application/vnd.github+json" \
                -d "{\"name\": \"${PROJECT_NAME}\", \"private\": false }" \
                https://api.github.com/user/repos

      ############################################################
      # 4. PUSH PROJECT TO NEW REPOSITORY
      ############################################################
      

  push-code:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
      - name: Download generated project
        uses: actions/download-artifact@v4
        with:
          name: generated-project
          path: workspace
      - name: Push project to new GitHub repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          USERNAME: ${{ secrets.GH_USERNAME }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
        run: |
          cd "workspace/${PROJECT_NAME}"
          git init
          git config user.email "ci-bot@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Initial Spring Boot project scaffolded automatically"
          git branch -M main
          git remote add origin https://${USERNAME}:${GH_PAT}@github.com/${USERNAME}/${PROJECT_NAME}.git
          git push -u origin main
